# Generated by Django 4.2 on 2023-05-03 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('booking_date', models.DateField()),
                ('no_of_guests', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('inventory', models.IntegerField()),
                ('price', models.IntegerField()),
                ('title', models.TextField(max_length=1000)),
            ],
        ),
    ]
